name = "alojinha"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "alojinha"
database_name = "alojinha"
database_id = "aca85cb1-0ff7-4c31-91a9-9c82db9ac3cb"

[vars]
ADMIN_PASSWORD = "alojinha2026"
