name = "alojinha"
main = "worker.js"

[[d1_databases]]
binding = "alojinha"
database_name = "alojinha"
database_id = "aca85cb1-0ff7-4c31-91a9-9c82db9ac3cb"

[vars]
AMAZON_TAG = "coloposte-20"
SHOPEE_AFF_ID = "18338650355"
MAGALU_STORE = "magazinehdmicroloja"
